// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAPIKeys implements APIKeyInterface
type FakeAPIKeys struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var apikeysResource = v1alpha1.SchemeGroupVersion.WithResource("apikeys")

var apikeysKind = v1alpha1.SchemeGroupVersion.WithKind("APIKey")

// Get takes name of the aPIKey, and returns the corresponding aPIKey object, and an error if there is any.
func (c *FakeAPIKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apikeysResource, c.ns, name), &v1alpha1.APIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIKey), err
}

// List takes label and field selectors, and returns the list of APIKeys that match those selectors.
func (c *FakeAPIKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apikeysResource, apikeysKind, c.ns, opts), &v1alpha1.APIKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APIKeyList{ListMeta: obj.(*v1alpha1.APIKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.APIKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPIKeys.
func (c *FakeAPIKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apikeysResource, c.ns, opts))

}

// Create takes the representation of a aPIKey and creates it.  Returns the server's representation of the aPIKey, and an error, if there is any.
func (c *FakeAPIKeys) Create(ctx context.Context, aPIKey *v1alpha1.APIKey, opts v1.CreateOptions) (result *v1alpha1.APIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apikeysResource, c.ns, aPIKey), &v1alpha1.APIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIKey), err
}

// Update takes the representation of a aPIKey and updates it. Returns the server's representation of the aPIKey, and an error, if there is any.
func (c *FakeAPIKeys) Update(ctx context.Context, aPIKey *v1alpha1.APIKey, opts v1.UpdateOptions) (result *v1alpha1.APIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apikeysResource, c.ns, aPIKey), &v1alpha1.APIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPIKeys) UpdateStatus(ctx context.Context, aPIKey *v1alpha1.APIKey, opts v1.UpdateOptions) (*v1alpha1.APIKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apikeysResource, "status", c.ns, aPIKey), &v1alpha1.APIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIKey), err
}

// Delete takes name of the aPIKey and deletes it. Returns an error if one occurs.
func (c *FakeAPIKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apikeysResource, c.ns, name, opts), &v1alpha1.APIKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPIKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apikeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APIKeyList{})
	return err
}

// Patch applies the patch and returns the patched aPIKey.
func (c *FakeAPIKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apikeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.APIKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIKey), err
}
