// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceAccountBindings implements ServiceAccountBindingInterface
type FakeServiceAccountBindings struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var serviceaccountbindingsResource = v1alpha1.SchemeGroupVersion.WithResource("serviceaccountbindings")

var serviceaccountbindingsKind = v1alpha1.SchemeGroupVersion.WithKind("ServiceAccountBinding")

// Get takes name of the serviceAccountBinding, and returns the corresponding serviceAccountBinding object, and an error if there is any.
func (c *FakeServiceAccountBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceaccountbindingsResource, c.ns, name), &v1alpha1.ServiceAccountBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceAccountBinding), err
}

// List takes label and field selectors, and returns the list of ServiceAccountBindings that match those selectors.
func (c *FakeServiceAccountBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceAccountBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceaccountbindingsResource, serviceaccountbindingsKind, c.ns, opts), &v1alpha1.ServiceAccountBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceAccountBindingList{ListMeta: obj.(*v1alpha1.ServiceAccountBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceAccountBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceAccountBindings.
func (c *FakeServiceAccountBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceaccountbindingsResource, c.ns, opts))

}

// Create takes the representation of a serviceAccountBinding and creates it.  Returns the server's representation of the serviceAccountBinding, and an error, if there is any.
func (c *FakeServiceAccountBindings) Create(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.CreateOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceaccountbindingsResource, c.ns, serviceAccountBinding), &v1alpha1.ServiceAccountBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceAccountBinding), err
}

// Update takes the representation of a serviceAccountBinding and updates it. Returns the server's representation of the serviceAccountBinding, and an error, if there is any.
func (c *FakeServiceAccountBindings) Update(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceaccountbindingsResource, c.ns, serviceAccountBinding), &v1alpha1.ServiceAccountBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceAccountBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceAccountBindings) UpdateStatus(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (*v1alpha1.ServiceAccountBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(serviceaccountbindingsResource, "status", c.ns, serviceAccountBinding), &v1alpha1.ServiceAccountBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceAccountBinding), err
}

// Delete takes name of the serviceAccountBinding and deletes it. Returns an error if one occurs.
func (c *FakeServiceAccountBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(serviceaccountbindingsResource, c.ns, name, opts), &v1alpha1.ServiceAccountBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceAccountBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceaccountbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceAccountBindingList{})
	return err
}

// Patch applies the patch and returns the patched serviceAccountBinding.
func (c *FakeServiceAccountBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceAccountBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceaccountbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServiceAccountBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceAccountBinding), err
}
