// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FlinkDeploymentListerExpansion allows custom methods to be added to
// FlinkDeploymentLister.
type FlinkDeploymentListerExpansion interface{}

// FlinkDeploymentNamespaceListerExpansion allows custom methods to be added to
// FlinkDeploymentNamespaceLister.
type FlinkDeploymentNamespaceListerExpansion interface{}

// WorkspaceListerExpansion allows custom methods to be added to
// WorkspaceLister.
type WorkspaceListerExpansion interface{}

// WorkspaceNamespaceListerExpansion allows custom methods to be added to
// WorkspaceNamespaceLister.
type WorkspaceNamespaceListerExpansion interface{}
