// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/compute/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FlinkDeploymentLister helps list FlinkDeployments.
// All objects returned here must be treated as read-only.
type FlinkDeploymentLister interface {
	// List lists all FlinkDeployments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FlinkDeployment, err error)
	// FlinkDeployments returns an object that can list and get FlinkDeployments.
	FlinkDeployments(namespace string) FlinkDeploymentNamespaceLister
	FlinkDeploymentListerExpansion
}

// flinkDeploymentLister implements the FlinkDeploymentLister interface.
type flinkDeploymentLister struct {
	indexer cache.Indexer
}

// NewFlinkDeploymentLister returns a new FlinkDeploymentLister.
func NewFlinkDeploymentLister(indexer cache.Indexer) FlinkDeploymentLister {
	return &flinkDeploymentLister{indexer: indexer}
}

// List lists all FlinkDeployments in the indexer.
func (s *flinkDeploymentLister) List(selector labels.Selector) (ret []*v1alpha1.FlinkDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FlinkDeployment))
	})
	return ret, err
}

// FlinkDeployments returns an object that can list and get FlinkDeployments.
func (s *flinkDeploymentLister) FlinkDeployments(namespace string) FlinkDeploymentNamespaceLister {
	return flinkDeploymentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FlinkDeploymentNamespaceLister helps list and get FlinkDeployments.
// All objects returned here must be treated as read-only.
type FlinkDeploymentNamespaceLister interface {
	// List lists all FlinkDeployments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FlinkDeployment, err error)
	// Get retrieves the FlinkDeployment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FlinkDeployment, error)
	FlinkDeploymentNamespaceListerExpansion
}

// flinkDeploymentNamespaceLister implements the FlinkDeploymentNamespaceLister
// interface.
type flinkDeploymentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FlinkDeployments in the indexer for a given namespace.
func (s flinkDeploymentNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FlinkDeployment, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FlinkDeployment))
	})
	return ret, err
}

// Get retrieves the FlinkDeployment from the indexer for a given namespace and name.
func (s flinkDeploymentNamespaceLister) Get(name string) (*v1alpha1.FlinkDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("flinkdeployment"), name)
	}
	return obj.(*v1alpha1.FlinkDeployment), nil
}
