// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/cloud/v1alpha1"
	scheme "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceAccountBindingsGetter has a method to return a ServiceAccountBindingInterface.
// A group's client should implement this interface.
type ServiceAccountBindingsGetter interface {
	ServiceAccountBindings(namespace string) ServiceAccountBindingInterface
}

// ServiceAccountBindingInterface has methods to work with ServiceAccountBinding resources.
type ServiceAccountBindingInterface interface {
	Create(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.CreateOptions) (*v1alpha1.ServiceAccountBinding, error)
	Update(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (*v1alpha1.ServiceAccountBinding, error)
	UpdateStatus(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (*v1alpha1.ServiceAccountBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ServiceAccountBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ServiceAccountBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceAccountBinding, err error)
	ServiceAccountBindingExpansion
}

// serviceAccountBindings implements ServiceAccountBindingInterface
type serviceAccountBindings struct {
	client rest.Interface
	ns     string
}

// newServiceAccountBindings returns a ServiceAccountBindings
func newServiceAccountBindings(c *CloudV1alpha1Client, namespace string) *serviceAccountBindings {
	return &serviceAccountBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceAccountBinding, and returns the corresponding serviceAccountBinding object, and an error if there is any.
func (c *serviceAccountBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	result = &v1alpha1.ServiceAccountBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceAccountBindings that match those selectors.
func (c *serviceAccountBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ServiceAccountBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ServiceAccountBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceAccountBindings.
func (c *serviceAccountBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceAccountBinding and creates it.  Returns the server's representation of the serviceAccountBinding, and an error, if there is any.
func (c *serviceAccountBindings) Create(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.CreateOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	result = &v1alpha1.ServiceAccountBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAccountBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceAccountBinding and updates it. Returns the server's representation of the serviceAccountBinding, and an error, if there is any.
func (c *serviceAccountBindings) Update(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	result = &v1alpha1.ServiceAccountBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		Name(serviceAccountBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAccountBinding).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *serviceAccountBindings) UpdateStatus(ctx context.Context, serviceAccountBinding *v1alpha1.ServiceAccountBinding, opts v1.UpdateOptions) (result *v1alpha1.ServiceAccountBinding, err error) {
	result = &v1alpha1.ServiceAccountBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		Name(serviceAccountBinding.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAccountBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceAccountBinding and deletes it. Returns an error if one occurs.
func (c *serviceAccountBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceAccountBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceAccountBinding.
func (c *serviceAccountBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ServiceAccountBinding, err error) {
	result = &v1alpha1.ServiceAccountBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serviceaccountbindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
