# Copyright (c) 2021 StreamNative, Inc.. All Rights Reserved.

# permissions for end users to view pulsarconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarconnection-viewer-role
rules:
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarconnections/status
  verbs:
  - get
