# Copyright (c) 2021 StreamNative, Inc.. All Rights Reserved.

# permissions for end users to edit pulsartenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsartenant-editor-role
rules:
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsartenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsartenants/status
  verbs:
  - get
