# permissions for end users to view pulsarpermissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarpermission-viewer-role
rules:
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarpermissions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pulsar.streamnative.io
  resources:
  - pulsarpermissions/status
  verbs:
  - get
