---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarconnections/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarfunctions/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarfunctions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsargeoreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsargeoreplications/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsargeoreplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarnamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpackages/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpermissions/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarpermissions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsinks/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsarsources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartenants/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartopics/finalizers
  verbs:
  - update
- apiGroups:
  - resource.streamnative.io
  resources:
  - pulsartopics/status
  verbs:
  - get
  - patch
  - update
