#!/usr/bin/env bash
# Copyright 2022 StreamNative
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Need to do these steps first
#   1. clone the repo streamnative/charts 
#   2. The value of env $CHART_PKG should be the path of `pulsar-resources-operator/.chart-packages`.
#   3. The directory of env $CHARTS_INDEX should be create first under the root path of repo charts.

BINDIR=`dirname "$0"`
# REPO_PATH is the path of pulsar-resources-operator
REPO_PATH=`cd ${BINDIR}/..;pwd`
# CHARTS_REPO_PATH is the path of charts
CHARTS_REPO_PATH=`cd ${REPO_PATH}/../charts;pwd`
OWNER=${OWNER:-streamnative}
REPO=${REPO:-charts}
GITHUB_TOKEN=${GITHUB_TOKEN:-"UNSET"}
GITUSER=${GITUSER:-"UNSET"}
GITEMAIL=${GITEMAIL:-"UNSET"}
# CHART_PKG is the path of pulsar-resources-operator chart package which is packaged in release.sh
CHART_PKG=${REPO_PATH}/.chart-packages
# CHARTS_INDEX is the path of index file which will be generated by update_chart_index()
CHARTS_INDEX=${CHARTS_REPO_PATH}/.chart-index
CR_BIN=${REPO_PATH}/output/bin/cr

RELEASE_BRANCH="$1"


function update_chart_index() {
    echo "Updating chart index..."
    ${CR_BIN} index -t ${GITHUB_TOKEN} --owner ${OWNER} --git-repo ${REPO} --package-path ${CHARTS_PKGS} --index-path ${CHARTS_INDEX}
}

function publish_charts() {
    git config user.email "${GITEMAIL}"
    git config user.name "${GITUSER}"
    git pull
    git checkout gh-pages
    cp --force ${CHARTS_INDEX}/index.yaml index.yaml
    git add index.yaml
    git commit --message="Publish new charts v${RELEASE_BRANCH:7}" --signoff
    git remote -v
    git remote add sn https://${SNBOT_USER}:${GITHUB_TOKEN}@github.com/${OWNER}/${REPO} 
    git push sn gh-pages 
}

update_chart_index
publish_charts