// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// APIKeyListerExpansion allows custom methods to be added to
// APIKeyLister.
type APIKeyListerExpansion interface{}

// APIKeyNamespaceListerExpansion allows custom methods to be added to
// APIKeyNamespaceLister.
type APIKeyNamespaceListerExpansion interface{}

// ClusterRoleListerExpansion allows custom methods to be added to
// ClusterRoleLister.
type ClusterRoleListerExpansion interface{}

// RoleBindingListerExpansion allows custom methods to be added to
// RoleBindingLister.
type RoleBindingListerExpansion interface{}

// RoleBindingNamespaceListerExpansion allows custom methods to be added to
// RoleBindingNamespaceLister.
type RoleBindingNamespaceListerExpansion interface{}

// SecretListerExpansion allows custom methods to be added to
// SecretLister.
type SecretListerExpansion interface{}

// SecretNamespaceListerExpansion allows custom methods to be added to
// SecretNamespaceLister.
type SecretNamespaceListerExpansion interface{}

// ServiceAccountListerExpansion allows custom methods to be added to
// ServiceAccountLister.
type ServiceAccountListerExpansion interface{}

// ServiceAccountNamespaceListerExpansion allows custom methods to be added to
// ServiceAccountNamespaceLister.
type ServiceAccountNamespaceListerExpansion interface{}

// ServiceAccountBindingListerExpansion allows custom methods to be added to
// ServiceAccountBindingLister.
type ServiceAccountBindingListerExpansion interface{}

// ServiceAccountBindingNamespaceListerExpansion allows custom methods to be added to
// ServiceAccountBindingNamespaceLister.
type ServiceAccountBindingNamespaceListerExpansion interface{}
