// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/cloud/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceAccountBindingLister helps list ServiceAccountBindings.
// All objects returned here must be treated as read-only.
type ServiceAccountBindingLister interface {
	// List lists all ServiceAccountBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceAccountBinding, err error)
	// ServiceAccountBindings returns an object that can list and get ServiceAccountBindings.
	ServiceAccountBindings(namespace string) ServiceAccountBindingNamespaceLister
	ServiceAccountBindingListerExpansion
}

// serviceAccountBindingLister implements the ServiceAccountBindingLister interface.
type serviceAccountBindingLister struct {
	indexer cache.Indexer
}

// NewServiceAccountBindingLister returns a new ServiceAccountBindingLister.
func NewServiceAccountBindingLister(indexer cache.Indexer) ServiceAccountBindingLister {
	return &serviceAccountBindingLister{indexer: indexer}
}

// List lists all ServiceAccountBindings in the indexer.
func (s *serviceAccountBindingLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceAccountBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceAccountBinding))
	})
	return ret, err
}

// ServiceAccountBindings returns an object that can list and get ServiceAccountBindings.
func (s *serviceAccountBindingLister) ServiceAccountBindings(namespace string) ServiceAccountBindingNamespaceLister {
	return serviceAccountBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ServiceAccountBindingNamespaceLister helps list and get ServiceAccountBindings.
// All objects returned here must be treated as read-only.
type ServiceAccountBindingNamespaceLister interface {
	// List lists all ServiceAccountBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceAccountBinding, err error)
	// Get retrieves the ServiceAccountBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ServiceAccountBinding, error)
	ServiceAccountBindingNamespaceListerExpansion
}

// serviceAccountBindingNamespaceLister implements the ServiceAccountBindingNamespaceLister
// interface.
type serviceAccountBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ServiceAccountBindings in the indexer for a given namespace.
func (s serviceAccountBindingNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceAccountBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceAccountBinding))
	})
	return ret, err
}

// Get retrieves the ServiceAccountBinding from the indexer for a given namespace and name.
func (s serviceAccountBindingNamespaceLister) Get(name string) (*v1alpha1.ServiceAccountBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("serviceaccountbinding"), name)
	}
	return obj.(*v1alpha1.ServiceAccountBinding), nil
}
