# Copyright (c) 2022 StreamNative, Inc.. All Rights Reserved.

apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: pulsartopic-sample
spec:
  # TODO(user): Add fields here
