// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	computev1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/compute/v1alpha1"
	clientset "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/client/clientset_generated/clientset"
	internalinterfaces "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/client/listers_generated/compute/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FlinkDeploymentInformer provides access to a shared informer and lister for
// FlinkDeployments.
type FlinkDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.FlinkDeploymentLister
}

type flinkDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFlinkDeploymentInformer constructs a new informer for FlinkDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFlinkDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFlinkDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFlinkDeploymentInformer constructs a new informer for FlinkDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFlinkDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComputeV1alpha1().FlinkDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComputeV1alpha1().FlinkDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&computev1alpha1.FlinkDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *flinkDeploymentInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFlinkDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *flinkDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&computev1alpha1.FlinkDeployment{}, f.defaultInformer)
}

func (f *flinkDeploymentInformer) Lister() v1alpha1.FlinkDeploymentLister {
	return v1alpha1.NewFlinkDeploymentLister(f.Informer().GetIndexer())
}
