// Copyright 2025 StreamNative
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/streamnative/pulsar-resources-operator/pkg/streamnativecloud/apis/compute/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFlinkDeployments implements FlinkDeploymentInterface
type FakeFlinkDeployments struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var flinkdeploymentsResource = v1alpha1.SchemeGroupVersion.WithResource("flinkdeployments")

var flinkdeploymentsKind = v1alpha1.SchemeGroupVersion.WithKind("FlinkDeployment")

// Get takes name of the flinkDeployment, and returns the corresponding flinkDeployment object, and an error if there is any.
func (c *FakeFlinkDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FlinkDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(flinkdeploymentsResource, c.ns, name), &v1alpha1.FlinkDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlinkDeployment), err
}

// List takes label and field selectors, and returns the list of FlinkDeployments that match those selectors.
func (c *FakeFlinkDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FlinkDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(flinkdeploymentsResource, flinkdeploymentsKind, c.ns, opts), &v1alpha1.FlinkDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FlinkDeploymentList{ListMeta: obj.(*v1alpha1.FlinkDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.FlinkDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested flinkDeployments.
func (c *FakeFlinkDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(flinkdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a flinkDeployment and creates it.  Returns the server's representation of the flinkDeployment, and an error, if there is any.
func (c *FakeFlinkDeployments) Create(ctx context.Context, flinkDeployment *v1alpha1.FlinkDeployment, opts v1.CreateOptions) (result *v1alpha1.FlinkDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(flinkdeploymentsResource, c.ns, flinkDeployment), &v1alpha1.FlinkDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlinkDeployment), err
}

// Update takes the representation of a flinkDeployment and updates it. Returns the server's representation of the flinkDeployment, and an error, if there is any.
func (c *FakeFlinkDeployments) Update(ctx context.Context, flinkDeployment *v1alpha1.FlinkDeployment, opts v1.UpdateOptions) (result *v1alpha1.FlinkDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(flinkdeploymentsResource, c.ns, flinkDeployment), &v1alpha1.FlinkDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlinkDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFlinkDeployments) UpdateStatus(ctx context.Context, flinkDeployment *v1alpha1.FlinkDeployment, opts v1.UpdateOptions) (*v1alpha1.FlinkDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(flinkdeploymentsResource, "status", c.ns, flinkDeployment), &v1alpha1.FlinkDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlinkDeployment), err
}

// Delete takes name of the flinkDeployment and deletes it. Returns an error if one occurs.
func (c *FakeFlinkDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(flinkdeploymentsResource, c.ns, name, opts), &v1alpha1.FlinkDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFlinkDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(flinkdeploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FlinkDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched flinkDeployment.
func (c *FakeFlinkDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FlinkDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(flinkdeploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FlinkDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FlinkDeployment), err
}
