#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Check License"
go test license_test.go
echo "Check Lint"
./scripts/lint.sh ./...
echo "Go fmt"
./scripts/verify_gofmt.sh ./...
echo "Go vet"
./scripts/verify_govet.sh ./...
