# Copyright (c) 2020 StreamNative, Inc.. All Rights Reserved.

name: Precommit Style Check
on:
  pull_request:
    branches:
      - '*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GOPRIVATE: github.com/streamnative
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Set up git token
      run: |
        git config --global url."https://${ACCESS_TOKEN}:@github.com/".insteadOf "https://github.com/"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check license
      run: |
        go test license_test.go

    - name: Check style
      run: |
        ./scripts/lint.sh ./...
        ./scripts/verify_gofmt.sh ./...
        ./scripts/verify_govet.sh ./...